name: Ejecutar script Python

on:
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub Actions
  push:               # También se ejecutará cada vez que hagas push
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Puedes cambiar la versión si lo deseas

      - name: Instalar dependencias
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Ejecutar el script Python
        run: python main.py
